apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-cicd-demo
  namespace: development
  labels:
    app: gha-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gha-cicd-demo
  template:
    metadata:
      labels:
        app: gha-cicd-demo
    spec:
      containers:
        - name: gha-cicd-demo
          image: ghcr.io/goswami97/gha-cicd-demo:48445d2210a1f2ab7e431afa09b4b0d872c8e823
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
