apiVersion: v1
kind: Service
metadata:
  name: gha-cicd-demo
  namespace: development
spec:
  type: NodePort
  selector:
    app: gha-cicd-demo
  ports:
    - port: 80
      targetPort: http
      nodePort: 30080
