apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-cicd-demo
  namespace: production
  labels:
    app: gha-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gha-cicd-demo
  template:
    metadata:
      labels:
        app: gha-cicd-demo
    spec:
      containers:
        - name: gha-cicd-demo
          image: ghcr.io/goswami97/gha-cicd-demo:9a333f4d0f928da87b6009bf13fe50d583df617d
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
