apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-cicd-demo
  namespace: qa
  labels:
    app: gha-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gha-cicd-demo
  template:
    metadata:
      labels:
        app: gha-cicd-demo
    spec:
      containers:
        - name: gha-cicd-demo
          image: ghcr.io/goswami97/gha-cicd-demo:2163fe94e78ba5aa2b1211ffd5519702681a2015
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
